services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
      target: php
      pull: true
    tmpfs:
      - /tmp
    volumes:
      - type: bind
        source: ./
        target: /app
        bind:
          create_host_path: true
      - type: bind
        source: ./settings.ini
        target: /usr/local/etc/php/conf.d/settings.ini
    environment:
      PHP_IDE_CONFIG: "serverName=cli"
      XDEBUG_CONFIG: "client_host=${CLIENT_HOST:-172.20.0.1} start_with_request=trigger idekey=${IDEKEY:-PHPSTORM}"
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      DNCSCRUB_PROJECT_ID: "${DNCSCRUB_PROJECT_ID:-UNDEFINED}"
      DNCSCRUB_LOGIN_ID: "${DNCSCRUB_LOGIN_ID:-UNDEFINED}"

